In [1]:
import numpy as np
import tensorflow as tf
from matplotlib.image import imread

In [2]:
# Load TFLite model and allocate tensors.
interpreter = tf.lite.Interpreter(model_path="converted_model.tflite")
interpreter.allocate_tensors()

In [3]:
# Get input and output tensors.
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()
print (input_details)
print (output_details)

[{'name': 'input_2', 'index': 1, 'shape': array([   1, 1280,  960,    3]), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0)}]
[{'name': 'Identity', 'index': 0, 'shape': array([   1, 1280,  960,    3]), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0)}]


In [4]:
# Test model on random input data.
input_shape = input_details[0]['shape']
input_data = np.array(np.random.random_sample(input_shape), dtype=np.float32)
interpreter.set_tensor(input_details[0]['index'], input_data)

In [6]:
interpreter.invoke()

In [7]:
# The function `get_tensor()` returns a copy of the tensor data.
# Use `tensor()` in order to get a pointer to the tensor.
output_data = interpreter.get_tensor(output_details[0]['index'])
print(output_data)

[[[[0.49925628 0.5001598  0.4984963 ]
   [0.49903715 0.49877366 0.49806157]
   [0.49898544 0.49895    0.49802288]
   ...
   [0.49884182 0.49759406 0.49637452]
   [0.49812686 0.49879685 0.4963755 ]
   [0.50031203 0.4995169  0.49946532]]

  [[0.4983644  0.4997666  0.49781802]
   [0.49821728 0.49988022 0.49807435]
   [0.49740458 0.49656314 0.4972742 ]
   ...
   [0.49636817 0.50128603 0.49656078]
   [0.497288   0.49730793 0.4967158 ]
   [0.49952468 0.50103635 0.4991206 ]]

  [[0.49918985 0.49933046 0.49852556]
   [0.49805653 0.49974656 0.49626848]
   [0.49492574 0.4974913  0.49512514]
   ...
   [0.4984287  0.49859372 0.49299735]
   [0.4986627  0.49720275 0.49561366]
   [0.49960887 0.4975459  0.49695322]]

  ...

  [[0.49692366 0.4987522  0.49638608]
   [0.49685496 0.5004872  0.49570468]
   [0.49424425 0.49798688 0.49532136]
   ...
   [0.49651083 0.50091845 0.49646944]
   [0.4976873  0.49889013 0.49607363]
   [0.4978342  0.49860084 0.49669734]]

  [[0.49832365 0.50025755 0.4966738 ]
   [0.4

In [11]:
image = imread('test_images/img_2.jpg', )
image = image.astype(float)
# tensor = tf.Variable(image, tf.float32)
interpreter.set_tensor(input_details[0]['index'], image)
interpreter.invoke()

ValueError: Cannot set tensor: Got value of type NOTYPE but expected type FLOAT32 for input 1, name: input_2 

In [9]:
input_details

[{'name': 'input_2',
  'index': 1,
  'shape': array([   1, 1280,  960,    3]),
  'dtype': numpy.float32,
  'quantization': (0.0, 0)}]

In [20]:
image = tf.convert_to_tensor(image, dtype=np.float32).numpy()

In [21]:
image.shape

(1280, 960, 3)

In [22]:
interpreter.set_tensor(input_details[0]['index'], image)


ValueError: Cannot set tensor: Dimension mismatch. Got 3 but expected 4 for input 1.

In [23]:
input_details[0]['index']

1